import { redirect, type Handle } from '@sveltejs/kit';

// prettier-ignore
const redirects: Record<string, string> = {
  '/add-unfiltered_html-capability-to-admins-or-editors-in-wordpress-multisite': '/blog/add-unfiltered_html-capability-to-admins-or-editors-in-wordpress-multisite',
  '/advanced-custom-fields-metabox-priority-for-top-above-publish': '/blog/advanced-custom-fields-metabox-priority-for-top-above-publish',
  '/advanced-custom-fields-wysiwyg-toolbar-buttons-missing': '/blog/advanced-custom-fields-wysiwyg-toolbar-buttons-missing',
  '/automate-trackpad-mouse-natural-scrolling-in-mac-os-x': '/blog/automate-trackpad-mouse-natural-scrolling-in-mac-os-x',
  '/bundle-load-testing-with-a-project': '/blog/bundle-load-testing-with-a-project',
  '/change-featured-image-title-link-text-wordpress': '/blog/change-featured-image-title-link-text-wordpress',
  '/change-wordpress-customizer-control-value-programmatically': '/blog/change-wordpress-customizer-control-value-programmatically',
  '/check-if-a-remote-image-file-exists-in-wordpress': '/blog/check-if-a-remote-image-file-exists-in-wordpress',
  '/check-if-user-exists-by-id-in-wordpress': '/blog/check-if-user-exists-by-id-in-wordpress',
  '/clear-selectize-control-on-dropdown-click': '/blog/clear-selectize-control-on-dropdown-click',
  '/copy-media-file-from-one-site-to-another-within-a-multisite-network': '/blog/copy-media-file-from-one-site-to-another-within-a-multisite-network',
  '/create-a-taxonomy-dropdown-in-wordpress': '/blog/create-a-taxonomy-dropdown-in-wordpress',
  '/delete-transients-with-prefix-in-wordpress': '/blog/delete-transients-with-prefix-in-wordpress',
  '/disable-cmb2-styles-front-end-forms': '/blog/disable-cmb2-styles-front-end-forms',
  '/display-woothemes-testimonials-avatar-before-quote': '/blog/display-woothemes-testimonials-avatar-before-quote',
  '/download-a-plugin-or-theme-from-the-wordpress-admin-dashboard': '/blog/download-a-plugin-or-theme-from-the-wordpress-admin-dashboard',
  '/download-insert-remote-image-file-wordpress-media-library': '/blog/download-insert-remote-image-file-wordpress-media-library',
  '/edit-slug-button-missing-in-wordpress': '/blog/edit-slug-button-missing-in-wordpress',
  '/find-all-pages-that-contain-a-gravity-form': '/blog/find-all-pages-that-contain-a-gravity-form',
  '/force-css-changes-to-go-live-immediately': '/blog/force-css-changes-to-go-live-immediately',
  '/get-a-list-of-all-wordpress-pages-that-contain-a-shortcode': '/blog/get-a-list-of-all-wordpress-pages-that-contain-a-shortcode',
  '/get-a-list-of-the-beaver-builder-modules-on-a-page': '/blog/get-a-list-of-the-beaver-builder-modules-on-a-page',
  '/get-all-gravity-forms-with-css-class': '/blog/get-all-gravity-forms-with-css-class',
  '/get-all-super-admin-users-in-wordpress': '/blog/get-all-super-admin-users-in-wordpress',
  '/get-blog-posts-page-url-permalink-wordpress': '/blog/get-blog-posts-page-url-permalink-wordpress',
  '/get-current-users-role-in-wordpress': '/blog/get-current-users-role-in-wordpress',
  '/get-file-type-url-remote-file-wordpress': '/blog/get-file-type-url-remote-file-wordpress',
  '/get-images-from-remote-server': '/blog/get-images-from-remote-server',
  '/get-main-site-url-wordpress-multisite-network': '/blog/get-main-site-url-wordpress-multisite-network',
  '/get-menu-modified-date-wordpress': '/blog/get-menu-modified-date-wordpress',
  '/get-page-template-post-wordpress-admin': '/blog/get-page-template-post-wordpress-admin',
  '/get-permalink-page-outside-the-loop': '/blog/get-permalink-page-outside-the-loop',
  '/get-post-author-in-wordpress': '/blog/get-post-author-in-wordpress',
  '/get-post-types-by-taxonomy-in-wordpress': '/blog/get-post-types-by-taxonomy-in-wordpress',
  '/get-root-domain-wordpress': '/blog/get-root-domain-wordpress',
  '/get-term-edited-term-php-wordpress-admin-page': '/blog/get-term-edited-term-php-wordpress-admin-page',
  '/get-the-excerpt-by-post-id-in-wordpress': '/blog/get-the-excerpt-by-post-id-in-wordpress',
  '/get-the-id-of-the-main-site-in-a-wordpress-multisite-network': '/blog/get-the-id-of-the-main-site-in-a-wordpress-multisite-network',
  '/get-the-slugs-for-all-fields-in-an-advanced-custom-fields-flexible-content-field': '/blog/get-the-slugs-for-all-fields-in-an-advanced-custom-fields-flexible-content-field',
  '/get-uploads-directory-path-in-wordpress': '/blog/get-uploads-directory-path-in-wordpress',
  '/get-url-users-buddypress-activity-stream-page': '/blog/get-url-users-buddypress-activity-stream-page',
  '/get-users-capabilities-in-wordpress': '/blog/get-users-capabilities-in-wordpress',
  '/get-users-first-last-name-wordpress': '/blog/get-users-first-last-name-wordpress',
  '/get-woocommerce-order-notes': '/blog/get-woocommerce-order-notes',
  '/include-featured-images-with-posts-using-wordpress-exportimport-tool': '/blog/include-featured-images-with-posts-using-wordpress-exportimport-tool',
  '/javascript-array-filter-indices': '/blog/javascript-array-filter-indices',
  '/load-template-from-wordpress-plugin': '/blog/load-template-from-wordpress-plugin',
  '/override-wordpress-rest-api-callbacks-protected-pages-posts': '/blog/override-wordpress-rest-api-callbacks-protected-pages-posts',
  '/php-make-an-array-of-objects-unique-by-comparing-a-property': '/blog/php-make-an-array-of-objects-unique-by-comparing-a-property',
  '/prepare-wordpress-theme-for-ssl': '/blog/prepare-wordpress-theme-for-ssl',
  '/prevent-svg-overflowing-div-container': '/blog/prevent-svg-overflowing-div-container',
  '/prism-one-dark-theme.css': '/blog/prism-one-dark-theme.css',
  '/remove-custom-post-type-slug-from-permalinks': '/blog/remove-custom-post-type-slug-from-permalinks',
  '/remove-line-breaks-wordpress': '/blog/remove-line-breaks-wordpress',
  '/rename-custom-post-type-in-wordpress': '/blog/rename-custom-post-type-in-wordpress',
  '/replace-post-meta-query-with-taxonomy-query': '/blog/replace-post-meta-query-with-taxonomy-query',
  '/require-post-title-for-custom-post-type': '/blog/require-post-title-for-custom-post-type',
  '/save-gravity-forms-file-upload-to-advanced-custom-fields-field-in-wordpress': '/blog/save-gravity-forms-file-upload-to-advanced-custom-fields-field-in-wordpress',
  '/set-image-caption-via-php-wordpress': '/blog/set-image-caption-via-php-wordpress',
  '/set-up-php-codesniffer-in-phpstorm-with-wordpress-coding-standards': '/blog/set-up-php-codesniffer-in-phpstorm-with-wordpress-coding-standards',
  '/set-up-ssl-locally-on-vvv-vagrant-wordpress-site': '/blog/set-up-ssl-locally-on-vvv-vagrant-wordpress-site',
  '/transfer-wordpress-org-plugin-ownership-committers': '/blog/transfer-wordpress-org-plugin-ownership-committers',
  '/vagrant-not-reachable-after-disconnecting-from-vpn': '/blog/vagrant-not-reachable-after-disconnecting-from-vpn',
  '/when-do-wordpress-unit-tests-run': '/blog/when-do-wordpress-unit-tests-run',
  '/wordpress-hook-options-page-save': '/blog/wordpress-hook-options-page-save',
  '/wordpress-user-query-not-working-with-ajax-wp-cron': '/blog/wordpress-user-query-not-working-with-ajax-wp-cron',
  '/wp-cli-search-replace-tables-skipped': '/blog/wp-cli-search-replace-tables-skipped',
};

export const handle: Handle = async ({ event, resolve }) => {
	const pathnameWithoutTrailingSlash = event.url.pathname.replace(/\/$/, '');
	if (redirects[pathnameWithoutTrailingSlash]) {
		throw redirect(301, redirects[pathnameWithoutTrailingSlash]);
	}

	return await resolve(event);
};
